#pragma once
void menuDisplay();
void addText();
void dispalyContent();
void emptyFile();
void encryptFile();
void decryptFile();
void Merge();
void countWords();
void countChars();
void countLines();
void searchWord();
void countWordExists();
void upperCase();
void lowerCase();
void contentCaps();
void save();